debug

diff --git a/.github/workflows/build_packages.yml b/.github/workflows/build_packages.yml
--- a/.github/workflows/build_packages.yml
+++ b/.github/workflows/build_packages.yml
@@ -22,26 +22,25 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v2
 
-      - name: Setup environnement
+      - name: Setup environment
         run: |
           set -e
           
           echo "=== Creating ROS workspace ... ==="
-          mkdir -p ros2_ws/src
+          mkdir -p ~/ros2_ws/src
           echo -e "\e[0;32m[OK]\e[0m"
 
           echo "=== Clone repo ... ==="
-          cd ros2_ws/src
+          cd ~/ros2_ws/src
           git clone https://github.com/${{ github.repository }}.git
-          cd
+          cd ..
           echo -e "\e[0;32m[OK]\e[0m"
 
           echo "=== Downloading and installing dependencies ... ==="
-          chmod + x ros2_ws/src/rover/scripts/provision.sh
-          ros2_ws/src/rover/scripts/provision.sh
+          chmod +x ~/ros2_ws/src/rover/scripts/provision.sh
+          ~/ros2_ws/src/rover/scripts/provision.sh
           echo -e "\e[0;32m[OK] Dependencies installed successfully\e[0m"
-        working-directory: "~"
-
+        
       - name: Building rover packages
         run: |
           echo "=== Sourcing for build ... ==="
@@ -53,9 +52,7 @@ jobs:
           if colcon build --event-handlers console_cohesion+; then
             echo "Build succeeded!"
             echo -e "\e[0;32m[SUCCESS]\e[0m"
-            exit 0
           else
             echo -e "\e[0;31m[FAILED] Building step triggered warnings or errors\e[0m"
+            exit 1  # Exit with status 1 if build fails
           fi
-
-          exit 1
